services:
  mongo1:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "voting_mongo_set"
      ]
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo:6
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "voting_mongo_set"
      ]
  mongo3:
    image: mongo:6
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "voting_mongo_set"
      ]
  votesache:
    container_name: votesache
    image: votingbackend
    restart: always
    volumes:
      - ./src/:/app/src
    ports:
      - 8000:8000
